update CI workflows (add to gurobi license check

diff --git a/.github/workflows/mac.yml b/.github/workflows/mac.yml
--- a/.github/workflows/mac.yml
+++ b/.github/workflows/mac.yml
@@ -19,6 +19,8 @@ jobs:
     runs-on: ${{ matrix.version.macos }}
     env:
       GUROBI_URL: ${{ secrets.GUROBI1302_OSX_URL }}
+      GUROBI_LICENSE_URL: ${{ secrets.GUROBI_LICENSE_URL }}
+      GRB_LICENSE_FILE: /Users/runner/gurobi.lic
       GUROBI_HOME: /Users/runner/lib/gurobi1302/macos_universal2
       DYLD_LIBRARY_PATH: /Users/runner/lib/gurobi1302/macos_universal2/lib
       soplex_DIR: /Users/runner/lib/soplex-7.1.6
@@ -47,6 +49,16 @@ jobs:
           rm "$RUNNER_TEMP/gurobi.pkg"
           test -f "$GUROBI_HOME/include/gurobi_c.h"
           test -d "$GUROBI_HOME/lib"
+
+      - name: Check Gurobi license
+        if: ${{ env.GUROBI_URL != 0 }}
+        run: |
+          wget -O "$GRB_LICENSE_FILE" "$GUROBI_LICENSE_URL" &> /dev/null
+          chmod 600 "$GRB_LICENSE_FILE"
+          if ! "$GUROBI_HOME/bin/gurobi_cl" --license; then
+            echo "Gurobi license is invalid or expired. Please contact gustavo.delazeri@unibas.ch"
+            exit 1
+          fi
 
       - name: Install SoPlex
         run: |
diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -37,6 +37,8 @@ jobs:
       CPLEX_LIB: /home/runner/lib/ibm/ILOG/CPLEX_Studio2211/cplex/bin/x86-64_linux/libcplex2211.so
 
       GUROBI_URL: ${{ secrets.GUROBI1302_LINUX_URL }}
+      GUROBI_LICENSE_URL: ${{ secrets.GUROBI_LICENSE_URL }}
+      GRB_LICENSE_FILE: /home/runner/gurobi.lic
       GUROBI_HOME: /home/runner/lib/gurobi1302/linux64
       GUROBI_LIB: /home/runner/lib/gurobi1302/linux64/lib
       LD_LIBRARY_PATH: /home/runner/lib/gurobi1302/linux64/lib
@@ -85,6 +87,17 @@ jobs:
           wget -O gurobi.tar.gz $GUROBI_URL &> /dev/null
           tar xfz gurobi.tar.gz -C /home/runner/lib
           rm gurobi.tar.gz
+
+      - name: Check Gurobi license
+        if: ${{ env.GUROBI_URL != 0 }}
+        run: |
+          # We redirect output of wget to hide the secret URL.
+          wget -O "$GRB_LICENSE_FILE" "$GUROBI_LICENSE_URL" &> /dev/null
+          chmod 600 "$GRB_LICENSE_FILE"
+          if ! "$GUROBI_HOME/bin/gurobi_cl" --license; then
+            echo "Gurobi license is invalid or expired. Please contact gustavo.delazeri@unibas.ch"
+            exit 1
+          fi
 
       # Always install SoPlex
       - name: Install SoPlex
